server:
  port: 8091
#随机算法
#provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#权重算法配置：
provider:
  ribbon:
    NFLoadBalancerRuleClassName:  com.java.xdh.config.NacosWeightedRule
rocketmq:
  name-server: 192.168.206.129:9876
