spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        enabled: false
  application:
    name: provider
server:
  port: 8016
management:
  endpoints:
    web:
      exposure:
        include: '*'
rocketmq:
  name-server: 192.168.206.129:9876
  producer:
    group: myprovider